# Generated by Django 2.2.10 on 2020-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200902_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='sections', through='articles.Relationship', to='articles.Article'),
        ),
    ]
